name: Deply to EC2, Encapmoments

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: EC2 배포
    runs-on: ubuntu-latest

    steps:
    - name: 레포지토리 클론
      uses: actions/checkout@v3

    #- name: Create .env file
    #  run: |
    #    echo "${{ secrets.ENV_FILE }}" > .env 

    - name: EC2 서버로 배포
      uses: appleboy/ssh-action@v1.0.0
      with:
        script_stop: true   # 실패 즉시 중단
        timeout: 60s # SSH 접속 시도 제한 시간 (연결 시도 제한) (기본값이 30초)
        command_timeout: 30m # 서버에 접속한 뒤, 스크립트 실행 시간 제한(명령 실행 제한)
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          set -euo pipefail
          set -x
          trap 'echo "❌ FAILED at line $LINENO: $BASH_COMMAND"' ERR
          port: 22
          APP_DIR=/home/ec2-user/encapmoments-backend
          BRANCH=main
          PM2_NAME=encap-backend

          cd "$APP_DIR"
          git checkout main
          git pull origin "$BRANCH"

          npm install --prefer-offline --no-audit --no-fund
          npx prisma migrate status
          npx prisma migrate deploy
          npx prisma generate  
          
          pm2 restart encap-backend

# CD test
# CD test하자!

